apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testargo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivakumar26011999/argo.git
    targetRevision: HEAD
    path: k8s-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default